[package]
name = "thaum-painter-entrypoint"
version = "0.1.2"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
thaum-painter-domain = { path = "../../domain" }
thaum-painter-workers = { path = "../../workers" }
thaum-renderer-boot = { path = "../../../thaum-renderer/orchestration/boot" }
thaum-renderer-domain = { path = "../../../thaum-renderer/domain" }
rfd = "0.15"
arboard = "3"
winit = "0.30"
